spring.datasource.url=jdbc:postgresql://localhost:5432/verifica_nf
spring.datasource.username=postgres
spring.datasource.password=!0Projetacs
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
